### ISSUE TITLE
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2537: FAILED: MQRC_CHANNEL_NOT_AVAILABLE

### ISSUE THREAD

**Issue by BrainMarine** [sensepost/punch-q#1]
Hi there,

Looks like a great tool you have there and I love.

However, I run into an error when using it. 

pymqi.MQMIError: MQI Error. Comp: 2, Reason 2537: FAILED: MQRC_CHANNEL_NOT_AVAILABLE

I did some googling, it seems that Common causes of this reason code are:
The channel is currently in stopped state.
The channel has been stopped by a channel exit.

The channel seems ok based on what I see.

Any suggestions on how can i resolve this error?

Thank you.

Execution log attached below.

root@kali:~/Desktop/MQTools# punch-q --dump-config --config config.yml discover channels
Effective configuration for this run:
-------------------------------------
Host:                  <ip address omitted>
Port:                  1414
Queue Manager Name:    None
Channel:               None
Username:              None
Password:              None

Traceback (most recent call last):
  File "/usr/local/bin/punch-q", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libpunchq/cli.py", line 273, in channels
    raise ce
pymqi.MQMIError: MQI Error. Comp: 2, Reason 2537: FAILED: MQRC_CHANNEL_NOT_AVAILABLE

**Comment by leonjza** [comment]
Hey,

I recently came across this as well and added a check for it in https://github.com/sensepost/punch-q/commit/10be5952ac5b8a612264708f3438523ec9d3ae68. You can just update punch-q with `pip install --upgrade punch-q` and check if that fixes it for you?

**Comment by BrainMarine** [comment]
That was a quick response. It's working fine now.
Thanks man!
